### ISSUE TITLE
Select .muxp file dialog box, should mask "*.muxp" files

### ISSUE THREAD

**Issue by marangonico** [nofaceinbook/muxp#34]
Select .muxp file dialog box, should mask "*.muxp" files

**Comment by nofaceinbook** [comment]
Not restricted to .muxp only, as current version also supports .kml files, and some leave the .yaml ending in order to have better support by editor. 
@marangonico please check if the commit https://github.com/nofaceinbook/muxp/commit/b5c0687f42dd8bc5191eeef1547b2f87ac1851cf is okay for you, so that we could close your issue

**Comment by marangonico** [comment]
Perfect. I'm closing the issue.
