### ISSUE TITLE
muxp hangs when executed with the target dsf already present

### ISSUE THREAD

**Issue by marangonico** [nofaceinbook/muxp#36]
muxp execution with the attached configuration is completed correctly on the first run (target dsf is absent).
If re-run for a second time, it hangs during the "cut_polygon.casera_1738" command processing.

[muxp_files.zip](https://github.com/nofaceinbook/muxp/files/4767653/muxp_files.zip)

**Comment by nofaceinbook** [comment]
Did apply the same changes to a dsf tile that was alrady changed? This will most often fail, especially on cut commands, as you enter then edge cases that are really hard to solve. That is the reason why muxp usually checks for conflicts of already applied updates to same area of mesh.
So when using e.g. IGNORE as conflict strategey it is recommended to always use the original dsf as source.

**Comment by marangonico** [comment]
I was simulating the user installing the mesh for a new scenery.
The .muxp was the one provided by you to be tested in combination with the .exe, and yes it has IGNORE as the conflict strategy.

Would it be possible to detect if the user has already applied a patch and warn it? Or skipping the generation?
Maybe storing the hash of the resulting dsf?

What do you think?

**Comment by nofaceinbook** [comment]
This detection is exactly what happens when idenifying conflicts. But not if you set conflictStrategy to IGNORE. Sorry, this was my fault. muxp.config should have the following entry:
conflictStrategy: ORIGINAL
This means that always the ORIGINGAL dsf is adapted, which will work. 
When you would like to skip set it to CANCEL.
When you leave it empty the ugly conflict GUI will come up and user can choose on his own.

muxp does store all applied changes in dsf properties keys inside the dsf file. You will see them relativly at the beginnig when you open an adapted dsf file.

BUT I just saw that the scenery is now added twice to scenery_packs.ini. I have to check this and leave this issue open....

**Comment by nofaceinbook** [comment]
Bug is set for adding scenery pack multiple times in scenery_pack.ini when activate pack is set to 1.

**Comment by marangonico** [comment]
If you agree, I'll check the scenery_packs.ini insert procedure.

**Comment by marangonico** [comment]
> muxp does store all applied changes in dsf properties keys inside the dsf file. You will see them relativly at the beginnig when you open an adapted dsf file.

So, in a deployment scenario, which  conflict strategy is suggested in order to keep previous mesh  patches?

**Comment by nofaceinbook** [comment]
This would be great. I have drunken wine and will not see errors any more ;-)
-------- Ursprüngliche Nachricht --------Von: marangonico <notifications@github.com> Datum: 12.06.20  22:50  (GMT+01:00) An: nofaceinbook/muxp <muxp@noreply.github.com> Cc: schmax <schmax@gmx.de>, Comment <comment@noreply.github.com> Betreff: Re: [nofaceinbook/muxp] muxp hangs when executed with the target dsf already present (#36) 
If you agree, I'll check the scenery_packs.ini insert procedure.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nofaceinbook/muxp/issues/36#issuecomment-643477758",
"url": "https://github.com/nofaceinbook/muxp/issues/36#issuecomment-643477758",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by marangonico** [comment]
LOL.. you are lucky then, I'm abstemious :-)
I'll create a new issue, I think you can close this one.
