### ISSUE TITLE
Simlink issues -linux

### ISSUE THREAD

**Issue by domrnet** [nofaceinbook/muxp#72]
Hi

I have all my ortho scenery on a separate drive but all directories sim linked to the custom scenery one. To do any editing I have to move my autho scenery folder to the custom scenery folder before I can select it to use. Is there any way to have MUXP use a fixed source for the dsf on another location?

**Comment by nofaceinbook** [comment]
Hi @domrnet , thanks for using muxp and sorry for my late reply. I had to read my manual myself because I'm not using X-Plane or muxp any more. In the configuration setttings there is the option to define a fixed source dsf. So you should be able to select here the ortho scenery you would like to adapt. However, I don't remember where the updated file will be written to. In case it is the zzzz_MUXP... folder than you need to make sure that it will have the right priority to be used. You might also get conflict warning because of other active mashes (described in the manual below). But there shold be ways to get this running. Just try....

**Comment by nofaceinbook** [comment]
You could also define the source dsf in your muxp-file (refer to page 37 of the manual). 
With regard to the active mesh there is some desription on page 9.
Ah, and you will still face the issue that when you update ortho mashes muxp will just replace it with some textures and not updating the ortho. So if you would still like to have orthographic area you could e.g. used drapped polygons for the airport definition.
Unfortunenately this is all not easy and my hope was that LR would have provided some easier ways to adapt terrain directly with XP12.

**Comment by domrnet** [comment]
Thanks for getting back.
I been moving the folder to the custom scenery folder in XP12 for the couple of areas I have been working on. That's fine and I can define the DSF with MUXP no problem. Once my work is done I copy the new dsf back to the autho folder and it works fine.
That is a bit of hassle so what I wanted to do was just define the DSF without having to actually move it to the custom scenery folder. The autho scenery is listed in the scenery ini file but because the scenery is on a another drive and simlinked to the actual custom scenery folder it does not show in the define dsf list in MUXP.  I don't think my original post explained so well sorry.
I thought I had missed something but maybe not. The dsf has to be directly in the custom scenery folder I guess?

**Comment by nofaceinbook** [comment]
Hi @domrnet I think I got your point but I forgot how muxp works. In my view you could enter any file for the source dsf but it seems it is only looking for defined scenery packs. So it will probably not work directly with you simlink. Sorry.

**Comment by domrnet** [comment]
yes seems you are right. thanks for feedback. The tool is doing a great job for me!
